In [20]:
import numpy as np
class meraPCA:
    def __init__(self,n):
        self.n=n
    
    def fit(self,X):
        X_std=X-np.mean(X,axis=0)
        self.mean = np.mean(X, axis=0)

        cov_matrix=np.cov(X_std,rowvar=False)
        eigenvalue,eigenvector=np.linalg.eig(cov_matrix)

        sorted_ind=np.argsort(eigenvalue)[::-1]
        self.components=eigenvector[:,sorted_ind[:self.n]]

    def transform(self, X):
        X_std = X - self.mean
        return np.dot(X_std, self.components)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)






X = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])


pca = meraPCA(2)
X_transformed = pca.fit_transform(X)

print("Original Data:\n", X)
print("Transformed Data (2 principal components):\n", X_transformed)
    

        


Original Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transformed Data (2 principal components):
 [[-7.79422863e+00  2.77555756e-16]
 [-2.59807621e+00  1.66533454e-16]
 [ 2.59807621e+00 -1.66533454e-16]
 [ 7.79422863e+00 -2.77555756e-16]]


In [18]:
import numpy as np

class PCA:
    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None

    def fit(self, X):
        # Step 1: Standardize the data (subtract mean and divide by std)
        self.mean = np.mean(X, axis=0)
        X_std = X - self.mean

        # Step 2: Compute the covariance matrix
        cov_matrix = np.cov(X_std, rowvar=False)

        # Step 3: Eigenvalue decomposition
        eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

        # Step 4: Sort eigenvalues and eigenvectors
        sorted_indices = np.argsort(eigenvalues)[::-1]
        self.components = eigenvectors[:, sorted_indices[:self.n_components]]

    def transform(self, X):
        # Project data onto the principal components
        X_std = X - self.mean
        return np.dot(X_std, self.components)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

# Example usage
if __name__ == "__main__":
    # Sample data (4 samples, 3 features)
    X = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

    # Apply PCA
    pca = PCA(n_components=2)
    X_transformed = pca.fit_transform(X)

    print("Original Data:\n", X)
    print("Transformed Data (2 principal components):\n", X_transformed)

Original Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transformed Data (2 principal components):
 [[-7.79422863e+00  2.77555756e-16]
 [-2.59807621e+00  1.66533454e-16]
 [ 2.59807621e+00 -1.66533454e-16]
 [ 7.79422863e+00 -2.77555756e-16]]
